version: '3.7'
services:
  os_db_container:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: 'parachute'
    ports:
      - 3306:3306
