
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parachute
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    serialization:
      fail-on-empty-beans: false